name: PR checklist
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - checklists/**/*

permissions:
  contents: write

jobs:
  OnlyUpdateLatestSchemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            checklists/**/*
      - name: Check only latest is updated
        env:
          CHANGED_FILES: ${{steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${CHANGED_FILES}; do
          if grep -qv "latest" <<< $file; then
          exit 1
          fi
          done
